title: Site

columns:
  - width: 1/2
    sections:
      preview: sections/preview
  - width: 1/2
    sections:
      pages:
        type: pages
        templates:
          - about
          - error
          - preview
          - signup