title: Site

columns:
  # - width: 1/2
  #   sections:
  #     preview: sections/preview
  - width: 1/2
    sections:
      pages:
        type: pages
        templates:
          - course
          - about
          - error
          - preview
          - signup